#!/bin/bash
chromium --temp-profile --start-maximized --mute-audio --load-extension=~/.config/chromium/Default/Extensions/cjpalhdlnbpafiamejdnhcphjbkeiagm/1.42.4_0,~/.config/chromium/Default/Extensions/ffbkglfijbcbgblgflchnbphjdllaogb/7.0.0_0&>/dev/null&
